[character]
symbol = "âœ"
error_symbol = "âœ–"
use_symbol_for_status = true

[directory]
truncation_length = 4

[jobs]
symbol = "ğŸƒ"
threshold = 0

[git_status]
staged_count.enabled = true
modified_count.enabled = true
untracked_count.enabled = true
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ğŸ’¨"
behind = "ğŸ¢"
diverged = "ğŸ”±"
untracked = "ğŸ›¤ï¸ "
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ—ƒï¸ "
renamed = "ğŸ“›"
deleted = "ğŸ—‘ï¸ "
prefix = ""
suffix = " "
style = "bright-white"

[memory_usage]
disabled = false
show_percentage = true
threshold = 50

[aws]
disabled = true

