[character]
success_symbol = "[âœ](green)"
error_symbol = "[âœ–](red)"

[directory]
truncation_length = 4

[jobs]
symbol = "ğŸƒ"

[git_status]
format = "[$all_status$ahead_behind]($style)"
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ğŸ’¨"
behind = "ğŸ¢"
diverged = "ğŸ”±"
untracked = "ğŸ›¤ï¸$count "
stashed = "ğŸ“¦"
modified = "ğŸ“$count "
staged = "ğŸ—ƒï¸$count "
renamed = "ğŸ“›"
deleted = "ğŸ—‘ï¸ "
style = "bright-white"

[memory_usage]
disabled = false
threshold = 50

[aws]
disabled = true

[python]
disabled = true
